export const COMMAND_TYPE_GENESIS = 0;
export const COMMAND_TYPE_CONFIG = 1;
export const COMMAND_TYPE_DB_SNAPSHOT = 2;

export const COMMAND_TYPE_KEY_POOLING = 20;

export const COMMAND_TYPE_TEST_VOTER_SIMPLE = 0xff01;
